export  const skills = [
  // Frontend
  { name: 'React', level: 90, category: 'Frontend' },
  { name: 'TypeScript', level: 90, category: 'Frontend' },
  { name: 'Tailwind CSS', level: 90, category: 'Frontend' },
  { name: 'Next.js', level: 80, category: 'Frontend' },
  { name: 'React Hook Form', level: 90, category: 'Frontend' },
  { name: 'React Query', level: 90, category: 'Frontend' },
  { name: 'REST API', level: 90, category: 'Frontend' },
  { name: 'MUI', level: 90, category: 'Frontend' },
  { name: 'AntDesign', level: 90, category: 'Frontend' },
  { name: 'Framer Motion', level: 90, category: 'Frontend' },
  { name: 'AOS', level: 95, category: 'Frontend' },
  { name: 'DaisyUI', level: 90, category: 'Frontend' },
  { name: 'Three.js', level: 90, category: 'Frontend' },
  { name: 'Axios', level: 90, category: 'Frontend' },
  { name: 'Context API', level: 90, category: 'Frontend' },
  { name: 'Zustand', level: 90, category: 'Frontend' },
  { name: 'Storybook', level: 90, category: 'Frontend' },
  { name: 'Shadcn', level: 85, category: 'Frontend' },
  { name: 'Hero UI', level: 80, category: 'Frontend' },

  // Tools
  { name: 'Git/GitHub', level: 90, category: 'Tools' },
  { name: 'VS Code', level: 95, category: 'Tools' },
  { name: 'Docker', level: 80, category: 'Tools' },
  { name: 'Figma', level: 85, category: 'Tools' },
  { name: 'Postman', level: 85, category: 'Tools' },
  { name: 'Cypress', level: 75, category: 'Tools' },
  { name: 'Jira', level: 95, category: 'Tools' },
  { name: 'Trello', level: 90, category: 'Tools' },
  { name: 'ClickUp', level: 80, category: 'Tools' },
  { name: 'Slack', level: 85, category: 'Tools' },
  { name: 'Swagger', level: 85, category: 'Tools' },
];