export const skills = [
  // Frontend
  { name: "JavaScript", category: "Frontend" },
  { name: "React", category: "Frontend" },
  { name: "TypeScript", category: "Frontend" },
  { name: "Tailwind CSS", category: "Frontend" },
  { name: "Next.js", category: "Frontend" },
  { name: "React Hook Form", category: "Frontend" },
  { name: "React Query", category: "Frontend" },
  { name: "REST API", category: "Frontend" },
  { name: "MUI", category: "Frontend" },
  { name: "AntDesign", category: "Frontend" },
  { name: "Framer Motion", category: "Frontend" },
  { name: "AOS", category: "Frontend" },
  { name: "DaisyUI", category: "Frontend" },
  { name: "Three.js", category: "Frontend" },
  { name: "Axios", category: "Frontend" },
  { name: "Context API", category: "Frontend" },
  { name: "Zustand", category: "Frontend" },
  { name: "Storybook", category: "Frontend" },
  { name: "Shadcn", category: "Frontend" },
  { name: "Hero UI", category: "Frontend" },

  // Tools
  { name: "Git/GitHub", category: "Tools" },
  { name: "VS Code", category: "Tools" },
  { name: "Docker", category: "Tools" },
  { name: "Figma", category: "Tools" },
  { name: "Postman", category: "Tools" },
  { name: "Unit Testing", category: "Tools" },
  { name: "Integration Testing", category: "Tools" },
  { name: "Jira", category: "Tools" },
  { name: "Trello", category: "Tools" },
  { name: "ClickUp", category: "Tools" },
  { name: "Slack", category: "Tools" },
  { name: "Swagger", category: "Tools" },
  { name: "Vercel", category: "Tools" },

  // Backend
  { name: "Node.js", category: "Backend" },
  // { name: "Express.js", category: "Backend" },
  { name: "Nest.js", category: "Backend" },
  { name: "PostgreSQL", category: "Backend" },
  { name: "REST API", category: "Backend" },
  { name: "JWT", category: "Backend" },
  { name: "OAuth", category: "Backend" },
];
